// @autogenerated
// Please do not edit this file directly

export * from './calls/getAmguPrice';
export * from './calls/getFundFactory';
export * from './transactions/deployMockVersion';
export * from './transactions/setAmguPrice';
export * from './transactions/setFundFactory';
export * from './transactions/setIsFund';
