const BigNumber = require('bignumber.js');

// Tokens

// Constants as defined in the token contracts
const PREMINED_AMOUNT = new BigNumber(Math.pow(10, 28));
const PREMINED_MELON_AMOUNT = new BigNumber(Math.pow(10, 28));

const ARAGONTOKEN_DECIMALS = 18;
const AVENTUSTOKEN_DECIMALS = 18;
const BANCORTOKEN_DECIMALS = 18;
const BASICATTENTIONTOKEN_DECIMALS = 18;
const BITCOINTOKEN_DECIMALS = 8;
const DIGIXDAOTOKEN_DECIMALS = 9;
const DIGIXGOLDTOKEN_DECIMALS = 9;
const DOGECOINTOKEN_DECIMALS = 8;
const ETHERCLASSICTOKEN_DECIMALS = 18;
const ETHERTOKEN_DECIMALS = 18;
const EUROTOKEN_DECIMALS = 8;
const GNOSISTOKEN_DECIMALS = 18;
const GOLEMTOKEN_DECIMALS = 18;
const ICONOMITOKEN_DECIMALS = 18;
const LITECOINTOKEN_DECIMALS = 8;
const MELONTOKEN_DECIMALS = 18;
const REPTOKEN_DECIMALS = 18;
const RIPPLETOKEN_DECIMALS = 6;
const STATUSTOKEN_DECIMALS = 18;

// Price Feed

// Liquidity Provider

const LIQUIDITY_PROVIDER = '0x00e0b33cdb3af8b55cd8467d6d13bc0ba8035acf';

// Exchange

const EXCHANGE_ADDRESS = '0x50396a51a81b938ccb2d1466de9eebc49d5564f5'

// Solidity constants
const ether = new BigNumber(Math.pow(10, 18));

module.exports = {
  ARAGONTOKEN_DECIMALS,
  AVENTUSTOKEN_DECIMALS,
  BANCORTOKEN_DECIMALS,
  BASICATTENTIONTOKEN_DECIMALS,
  BITCOINTOKEN_DECIMALS,
  DIGIXDAOTOKEN_DECIMALS,
  DIGIXGOLDTOKEN_DECIMALS,
  DOGECOINTOKEN_DECIMALS,
  ETHERCLASSICTOKEN_DECIMALS,
  ETHERTOKEN_DECIMALS,
  EUROTOKEN_DECIMALS,
  GNOSISTOKEN_DECIMALS,
  GOLEMTOKEN_DECIMALS,
  ICONOMITOKEN_DECIMALS,
  LITECOINTOKEN_DECIMALS,
  MELONTOKEN_DECIMALS,
  REPTOKEN_DECIMALS,
  RIPPLETOKEN_DECIMALS,
  STATUSTOKEN_DECIMALS,
  PREMINED_AMOUNT,
  PREMINED_MELON_AMOUNT,
  LIQUIDITY_PROVIDER,
  EXCHANGE_ADDRESS,
  ether,
};
