export const tokenInfo = {
  kovan: [
    {
      address: '0xD99aED09A65ee8377A2fFad8ED5407785c530869',
      name: 'Aragon Network Token',
      symbol: 'ANT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '0x20A0E0dECE9FB6C690CdB439db2B385d271BdA3f',
      name: 'AventCoin',
      symbol: 'AVT-T',
      decimals: 18,
      url: 'https://aventus.io/',
      githubHint: '',
    },
    {
      address: '',
      name: 'Bancor Network Token',
      symbol: 'BNT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Basic Attention Token',
      symbol: 'BAT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Bitcoin Token',
      symbol: 'BTC-T',
      decimals: 8,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Digix Dao Token',
      symbol: 'DGD-T',
      decimals: 9,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Digix Gold Token',
      symbol: 'DGX-T',
      decimals: 9,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Dogecoin Token',
      symbol: 'DOGE-T',
      decimals: 8,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Ether Classic Token',
      symbol: 'ETC-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Ether Token',
      symbol: 'ETH-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Aragon Network Token',
      symbol: 'ANT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Euro Token',
      symbol: 'EUR-T',
      decimals: 8,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Gnosis Token',
      symbol: 'GNO-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Golem Network Token',
      symbol: 'GNT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Iconomi Token',
      symbol: 'ICN-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Litecoin Token',
      symbol: 'LTC-T',
      decimals: 8,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Melon Token',
      symbol: 'MLN-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'MakerDAO Token',
      symbol: 'MKR-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Rep Token',
      symbol: 'REP-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Ripple Token',
      symbol: 'XRP-T',
      decimals: 6,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'SingularDTV Token',
      symbol: 'SNGLS-T',
      decimals: 0,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: 'Status Network Token',
      symbol: 'SNT-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
    {
      address: '',
      name: '0x Protocol Token',
      symbol: 'ZRX-T',
      decimals: 18,
      url: '',
      githubHint: '',
    },
  ],
};
